# Generated by Django 3.1.1 on 2020-11-11 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import party.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='파티 이름')),
                ('place', models.CharField(max_length=50, verbose_name='파티 장소')),
                ('description', models.TextField(verbose_name='파티 설명')),
                ('opendate', models.TimeField(verbose_name='개최 시간')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='이름(별명)')),
                ('image', party.fields.ThumbnailImageField(upload_to='photo/%Y/%m', verbose_name='이미지')),
                ('join_dt', models.DateTimeField(auto_now_add=True, verbose_name='참석 날짜')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.partyname')),
            ],
            options={
                'ordering': ('nickname',),
            },
        ),
    ]
