# Generated by Django 3.1.1 on 2020-09-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(null=True, verbose_name='학번')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='GROUP')),
                ('tel', models.CharField(max_length=50, verbose_name='MOBILE')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='EMAIL')),
                ('birth_dt', models.DateTimeField(verbose_name='COMPANY')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
            options={
                'ordering': ('student_id', 'name'),
            },
        ),
    ]
