# Generated by Django 3.1.1 on 2020-10-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_time',
            field=models.CharField(blank=True, max_length=30, verbose_name='강의시간'),
        ),
    ]
