# Generated by Django 3.1.1 on 2020-10-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0003_auto_20201030_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugang_student',
            old_name='Subject',
            new_name='subject',
        ),
    ]
